---
version: '2'
services:
  #SubscriptionNews operational db
  subscription-news-operational-db:
    image: postgres:13.3
    container_name: subscription-news-operational-db
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription-news-db
    ports:
      - "5433:5432"
